### ISSUE TITLE
Expected final separator CR LF CR LF, but got: 13 10 87 65

### ISSUE THREAD

**Issue by martinsbalodis** [ept/warc-hadoop#2]
Got this error while content from a _revisit_ entry was read. Probably the problem is that there is a missing empty line that the library expected. `13 10 87 65` equals `<CR><LF>WA`. Usually there are 3 empty lines or 4 `\r\n` symbols. Maybe the problem is on my side because I was using a Heritrix version compiled from source/master.

Here is the entry from warc file:

```
WARC/1.0
WARC-Type: revisit
WARC-Target-URI: http://parstipru.lv/forums/rss/forum/testa-ieraksts/topics
WARC-Date: 2014-03-10T02:17:25Z
WARC-Payload-Digest: sha1:3I42H3S6NNFQ2MSVX7XZKYAYSCX5QBYJ
WARC-IP-Address: 159.148.127.206
WARC-Profile: http://netpreserve.org/warc/1.0/revisit/server-not-modified
WARC-Etag: "d41d8cd98f00b204e9800998ecf8427e"
WARC-Truncated: length
WARC-Record-ID: <urn:uuid:a3d332c0-30ef-4f9d-a622-e6d3af511ec9>
Content-Length: 0


WARC/1.0
WARC-Type: request
...
```

Here is the stack trace:

```
java.lang.Exception: java.lang.IllegalStateException: Expected final separator CR LF CR LF, but got: 13 10 87 65
    at org.apache.hadoop.mapred.LocalJobRunner$Job.run(LocalJobRunner.java:400)
Caused by: java.lang.IllegalStateException: Expected final separator CR LF CR LF, but got: 13 10 87 65
    at com.martinkl.warc.WARCRecord.readSeparator(WARCRecord.java:101)
    at com.martinkl.warc.WARCRecord.<init>(WARCRecord.java:50)
    at com.martinkl.warc.WARCFileReader.read(WARCFileReader.java:54)
    at com.martinkl.warc.mapred.WARCInputFormat$WARCReader.next(WARCInputFormat.java:72)
    at com.martinkl.warc.mapred.WARCInputFormat$WARCReader.next(WARCInputFormat.java:52)
```

Thanks for the great warc-hadoop library!

**Comment by ept** [comment]
Thanks for the report, and sorry for the long-delayed reply. It looks to me like the file format is not correct: according to [the spec](http://bibnum.bnf.fr/warc/WARC_ISO_28500_version1_latestdraft.pdf), a zero-length record should have four sets of `\r\n` (two to separate the header from the body, and another two to separate the body from the next record). Your example only seems to have three.

Perhaps this is something we should handle in the library. When I was looking at other WARC parsing libraries (before I started writing this one), I vaguely remember seeing a source comment somewhere about tolerating fewer `\r\n`s due to some program generating incorrect output. However, the better solution would probably be to fix the program that's generating the invalid WARC, if possible. Is that Heritrix in your case?
